"""Add email and error_message to EmailLog

Revision ID: e94ba5b3824d
Revises: 
Create Date: 2025-08-07 23:51:40.953946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94ba5b3824d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.alter_column('subscriber_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.alter_column('subscriber_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('error_message')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
